### ISSUE TITLE
Test doesn't pass because Strapi timeout

### ISSUE THREAD

**Issue by Kazdan1994** [qunabu/strapi-unit-test-example#1]
Hi,

After pulling your repo, I try to run test and got these errors.

[2020-06-03T10:04:03.051Z] warn The bootstrap function is taking unusually long to execute (3500 miliseconds).
[2020-06-03T10:04:03.055Z] warn Make sure you call it?
[2020-06-03T10:04:05.791Z] debug POST /auth/local (1316 ms) 200
 FAIL  tests/app.test.js (11.972 s)
  ✕ strapi is defined (6 ms)
  ✕ should return hello world (5 ms)
  ✕ should login user and return jwt token (4221 ms)
  ✕ should return users data for authenticated user (220 ms)

  ● strapi is defined

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:29:45)

  ● should return hello world

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:29:45)

  ● should return hello world

    TypeError: Cannot read property 'address' of undefined

      3 | it("should return hello world", async (done) => {
      4 |   await request(strapi.server) // app server is and instance of Class: http.Server
    > 5 |     .get("/hello")
        |      ^
      6 |     .expect(200) // Expect response http code 200
      7 |     .then((data) => {
      8 |       expect(data.text).toBe("Hello World!"); // expect the response text

      at Test.serverAddress (node_modules/supertest/lib/test.js:55:18)
      at new Test (node_modules/supertest/lib/test.js:36:12)
      at Object.get (node_modules/supertest/index.js:25:14)
      at Object.<anonymous> (tests/hello/index.js:5:6)

  ● should login user and return jwt token

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:29:45)

  ● should return users data for authenticated user

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:29:45)

Test Suites: 1 failed, 1 total
Tests:       4 failed, 4 total
Snapshots:   0 total
Time:        12.078 s, estimated 14 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Can you answer if it's my fail or a problem with your repo. Thank you !

**Comment by qunabu** [comment]
Had just run test on my machine MacOs, node v12.16.1
```bash 
git clone https://github.com/qunabu/strapi-unit-test-example.git
Cloning into 'strapi-unit-test-example'...
remote: Enumerating objects: 97, done.
remote: Counting objects: 100% (97/97), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 97 (delta 20), reused 96 (delta 19), pack-reused 0
Unpacking objects: 100% (97/97), done.
➜  localhost cd strapi-unit-test-example
➜  strapi-unit-test-example git:(master) yarn
yarn install v1.13.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "strapi-admin > bootstrap@4.5.0" has unmet peer dependency "jquery@1.9.1 - 3".
warning "strapi-admin > bootstrap@4.5.0" has unmet peer dependency "popper.js@^1.16.0".
warning "strapi-admin > @buffetjs/core > react-dates@21.8.0" has unmet peer dependency "react-with-direction@^1.3.1".
warning " > strapi-connector-bookshelf@3.0.0" has incorrect peer dependency "knex@^0.20.0".
warning "strapi-plugin-users-permissions > grant-koa@5.1.1" has unmet peer dependency "koa@>=2.0.0".
[5/5] 🔨  Building fresh packages...
✨  Done in 23.44s.
➜  strapi-unit-test-example git:(master) yarn test
yarn run v1.13.0
$ jest --forceExit --detectOpenHandles
[2020-06-03T10:12:08.745Z] debug GET /hello (10 ms) 200
[2020-06-03T10:12:09.798Z] debug POST /auth/local (902 ms) 200
 PASS  tests/app.test.js (7.692 s)
  ✓ strapi is defined (2 ms)
  ✓ should return hello world (53 ms)
  ✓ should login user and return jwt token (1050 ms)
  ✓ should return users data for authenticated user (157 ms)

Test Suites: 1 passed, 1 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        7.764 s
Ran all test suites.
```

Called `yarn test` many times, without getting this error 

Is there any other environment settings i can test this against ?

**Comment by mithuns14** [comment]
same timeout error for me. what are all the changes required when using **npm** with **mysql database**

**Comment by rubenzup** [comment]
maybe isnt working because its running on windows?

**Comment by qunabu** [comment]
Can you provide an environment I can replicate this error?

**Comment by mithuns14** [comment]
Windows 10 64 bit
Node: 13.8.0

*await Strapi().load();* strapi can't be loaded using await keyword

so

it("strapi is defined", async () => {
  expect(strapi).toBeDefined();
  done();
});

above test case failing. when i am running  *Strapi().load(); *instead
of *await
Strapi().load(); t*he test case got passed.

but that is not the actual issue.

Could you please help me

**Comment by mithuns14** [comment]
**Windows 10 64 bit
Node: 13.8.0**



1. it("strapi is defined", async () => {
   expect(strapi).toBeDefined();
   done();
  });

above test case failing.

2. When i am running  **Strapi().load();** instead of **await Strapi().load();** the test case got passed.

but that is not the actual issue.

3. I am not able to test the end points too

**Comment by rubenzup** [comment]
@mithuns14  same here, it seems isnt acessing the db

**Comment by mithuns14** [comment]
@qunabu: Could you please look into this, and suggest a solution

**Comment by qunabu** [comment]
Can you try with latest pulls and let me know if anything has changed. 

Also I've just add a CircleCI for reports on those test.

**Comment by mithuns14** [comment]
I will check and let you know. I am using MySQL as a database, so what's the main thing I need to change

**Comment by qunabu** [comment]
It does work in [CI/CD environment](https://circleci.com/gh/qunabu/strapi-unit-test-example)

**Comment by mithuns14** [comment]
how the test *"filename": ".tmp/test.db" *file can be configured for* mysql
*database. Is it using real database ?

**Comment by qunabu** [comment]
This example is as simple as possible - so it is just for sqlite. 

In order to have tests for `mysql`, `postgres` or `mongo` you would need to have a separate database just for tests. Each test would require to clear it from any data. 

Therefore @mithuns14 - this question is unrelated, please create another issue or follow the [tutorial](https://strapi.io/documentation/v3.x/guides/databases.html) - everything you asking is there, yet I'm not planning to put `mysql` example in this repo.

**Comment by qunabu** [comment]
@Kazdan1994 @rubenzup can you check again with updated code.

**Comment by rubenzup** [comment]
Thank you so much for the attention! We are also using docker-compose with env files, to a PostgreSQL database in Amazon RDS, and thats the problem too, we cant figure out if the problem is in docker-compose file, or any configuration

**Comment by rubenzup** [comment]
its funny cause when i change a test for something like 

```
it('should return Header', async (done) => {
  await request('http://localhost:1337') // app server is an instance of Class: http.Server
    .get('/header')
    .expect(200) // Expect response http code 200
    .then((data) => {
      const json = JSON.parse(data.text);
      console.log('json', json)
      expect(json.link[0].Title).toBe('Header'); // expect the response text
    });
  done();
});
```

getting from localhost, instead of strapi.server it works. With docker running strapi

**Comment by Kazdan1994** [comment]
Hi everyone. I have a fix, just change your app.test.js inside tests folder with

```javascript

const fs = require("fs");
const { setupStrapi } = require("./helpers/strapi");

jest.setTimeout(10000);

/** this code is called once before any test is called */
beforeAll(async () => {
  await setupStrapi(); // singleton so it can be called many times
});

/** this code is called once before all the tested are finished */
afterAll(async (done) => {
  const dbSettings = strapi.config.get("database.connections.default.settings");

  //delete test database after all tests
  if (dbSettings && dbSettings.filename) {
    const tmpDbFile = `${__dirname}/../${dbSettings.filename}`;
    if (fs.existsSync(tmpDbFile)) {
      fs.unlinkSync(tmpDbFile);
    }
  }
  done();
});

it("strapi is defined", async (done) => {
  expect(strapi).toBeDefined();
  done();
});

require("./hello");
require("./user");
```

jest timeout need to be increase with strapi in some case. Hope you have a great day and thanks for your replies.

**Comment by qunabu** [comment]
@Kazdan1994 can you create MR with fixed code ?

**Comment by rubenzup** [comment]
ok @Kazdan1994  but, is im using a db like Postrgres, and i have a test.db at tmp folder, does, Jest/Strapi understands it have to get this file instead of my PostgresSQL?

cause If i dont run strapi, my tests doesnt pass

**Comment by rubenzup** [comment]
![image](https://i.imgur.com/fbvOYtQ.png)

**Comment by Kazdan1994** [comment]
Hi. Sorry I close this issue since I fork the repository and add some fix. You can download fixed version at git@github.com:Kazdan1994/strapi-unit-test-example.git.

Your problem is due to jest, who timeout at 5000ms. So strapi isn't load and the instance is undefined. And your tests failed because you call method like services or query on undefined.

So the solution is just to increase the jest timeout.
