### ISSUE TITLE
Strapi not loading for tests in pipeline

### ISSUE THREAD

**Issue by mfelix5** [qunabu/strapi-unit-test-example#17]
Hi there, using this general pattern for unit tests has worked for me so far. I can run unit tests as expected locally using `npm run test`. However, trying to run the same command in a bitbucket pipeline, I end up with an error:

  console.error
    Unhandled error
      at process.uncaught (node_modules/jest-jasmine2/build/jasmine/Env.js:248:21)

I believe this is because Strapi is not loading successfully here: https://github.com/qunabu/strapi-unit-test-example/blob/6e1fa022f2de0d6aa70f718063fbb162d840bd22/tests/helpers/strapi.js#L13

I note that I get the same error locally if I comment out the Jest timeout: https://github.com/qunabu/strapi-unit-test-example/blob/6e1fa022f2de0d6aa70f718063fbb162d840bd22/tests/helpers/strapi.js#L5 

Here are the contents of my bitbuckets-pipeline.yml file: 

image: node:12.18.4

definitions:
  step: &build
    name: test and build
    caches:
      - node
    script:
      - apt-get update && apt-get install -y zip unzip
      - npm install
      - npm run test
      - npm run build
      - zip application.zip . -r * .[^.]*
    artifacts:
      - application.zip
pipelines:      
  default:
    - step: *build
  branches: 
    master:
    - step: *build
    - step:
        name: Deploy master to Production env
        script:
          - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: "us-east-2"
              APPLICATION_NAME: "trapi-prod"
              ENVIRONMENT_NAME: 'production'
              ZIP_FILE: "application.zip"
    dev:
      - step: *build
      - step:
          name: Deploy dev to Development env
          script:
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: "us-east-2"
                APPLICATION_NAME: "trapi-dev"
                ENVIRONMENT_NAME: 'development'
                ZIP_FILE: "application.zip"

Any insight is appreciated. 

Thanks!

**Comment by qunabu** [comment]
I no longer get this kind of errors with my current setup, but I've used to get this as well. 

My first guess is that bitbucket runner doesn't have enough resources, ram mostly. 

This repository is attached to circle.ci and does not throw any errors like that anymore, you can clone it and try in on your circle.ci - public projects are free.

**Comment by qunabu** [comment]
Can you try increasing memory in your pipe - https://support.atlassian.com/bitbucket-cloud/docs/databases-and-service-containers/ and see if it correlate

**Comment by mfelix5** [comment]
Thanks, I tried doubling the memory and got the same behavior. That said, your suspicion seems logical. Since I last posted we have decided to move away from Strapi. It's not the right tool for our project at this point.

**Comment by qunabu** [comment]
The later the versions are better it is. What version your using in your project ?

**Comment by qunabu** [comment]
@mfelix5 is your issue still pending ?

**Comment by mfelix5** [comment]
No it is not. We ended up moving away from Strapi. Thanks for checking back though.
