### ISSUE TITLE
Strapi Unit Test Helpers as NPM Library

### ISSUE THREAD

**Issue by fchristl** [qunabu/strapi-unit-test-example#56]
I just saw your talk on Strapi Conf and love the potential of your unit test helpers for our projects. Combined with Strapi's upcoming TS support, proper testing is what we're missing to build larger non-CMS backend projects with Strapi.

It's already great that we have this repo, thank you for that 🙏! 

On top of that, it'd be great if you'd publish the helpers as an NPM library. That'd make setting up projects with proper unit tests much more pleasant, plus remove the maintenance burden of having to copy over files into the individual repos.

**Comment by qunabu** [comment]
Sorry, i don't have time this year to work on this, but I'm happy to review any Pull Request
