### ISSUE TITLE
Jest fails on strapi versions >=4.0.8

### ISSUE THREAD

**Issue by MorganeLeCaignec** [qunabu/strapi-unit-test-example#58]
Hello, thank you for this functioning example of Strapi V4 + Jest !

I'm trying to run this with Typescript as well, and I ran into a ton of weird errors.
While debugging, I tried removing all .ts and TS-related stuff from my own project to try and recreate this one and see if I could get it to work without TS (then gradually add stuff back to see where the problem comes from).

I realized that my @strapi/strapi (and related libraries) is a higher version than this one.

This project uses version `4.0.7` and works.
Updating to higher versions (even just version `4.0.8`) fails for me.
I'd like to get it to work with version `4.3.5` ideally.

I don't know if this will also fix the errors I'm getting with typescript but it would be a good start, and I could at the very least run Strapi V4 + Jest without Typescript (and maybe add typescript back later).

Has anyone tried running this on higher @strapi/strapi versions and gotten it to work ?

**Comment by qunabu** [comment]
I'll try to have a look on this version of Stripe soon

**Comment by qunabu** [comment]
main branch is updated to work on `4.3.6`

**Comment by qunabu** [comment]
TypeScript test are here https://github.com/qunabu/strapi-unit-test-example/tree/ver4ts
