### ISSUE TITLE
test fails

### ISSUE THREAD

**Issue by mithuns14** [qunabu/strapi-unit-test-example#6]
![UT error](https://user-images.githubusercontent.com/20041309/87857785-0c090480-c947-11ea-944d-e639869b8e94.PNG)

**Comment by JuanmanDev** [comment]
I also have the same problem.
I am looking around and fin that sqlite should not have more than 1 connection, so, first:
Go to `config\env\test\database.json` and change max pool to 1:
```json
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "bookshelf",
      "settings": {
        "client": "sqlite",
        "filename": ".tmp/test.db"
      },
      "options": {
        "useNullAsDefault": true,
        "pool": {
          "min": 0,
          "max": 1      /* <<<<<<< HERE   (remove this comment!) */
        }
      }
    }
  }
}
```

After that, i still having problems:
This first one:
![image](https://user-images.githubusercontent.com/5569316/87889229-db04fe80-ca30-11ea-8aaa-ef607f1ccad9.png)

Second seems to be not imporant (it repeats about 5 times):
![image](https://user-images.githubusercontent.com/5569316/87889250-ee17ce80-ca30-11ea-8283-a5fe72090f35.png)

Third is connection to strapi tracker, so it should be ignored thought:
![image](https://user-images.githubusercontent.com/5569316/87889274-17385f00-ca31-11ea-91ee-2dde2543fd45.png)

and then....
![image](https://user-images.githubusercontent.com/5569316/87889350-6bdbda00-ca31-11ea-944a-ae190e235e68.png)


I'm working on Windows 10 2004.
Node 12.18.2

After updating Strapi to 3.0.6 the error of EBUSY sqlite is there.

**Comment by Kazdan1994** [comment]
The tests doesn't pass after upgrade Strapi to 3.0.6. I forked the repository and try to fix this issue.

**Comment by Kazdan1994** [comment]
I have a fix to submit by PR. just open config/test/database.json and remove pool options

```json
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "bookshelf",
      "settings": {
        "client": "sqlite",
        "filename": ".tmp/test.db"
      },
      "options": {
        "useNullAsDefault": true
      }
    }
  }
}
```

**Comment by qunabu** [comment]
The repository was updated to `^3.1` please check again 

Also you can see results of the tests https://app.circleci.com/pipelines/github/qunabu/strapi-unit-test-example
