### ISSUE TITLE
SQLLite Error and strapi.store is not a function

### ISSUE THREAD

**Issue by callum-gander** [qunabu/strapi-unit-test-example#61]
Hi,

So, I've been trying to get unit tests for v4 running using this example and there seems be be some issue with the code for me. When I copy it exactly as is I get the following error

create table `public`.`strapi_migrations` (`id` integer not null primary key autoincrement, `name` varchar(255), `time` datetime) - SQLITE_ERROR: unknown database `public` (ignore the weird formatting)

which implies that Strapi().load() is not populating the test.db properly. When I change `Strapi().load()` to `Strapi()` it seems to remedy this issue, or at least get rid of the error, but I can't be sure it's actually populating the table correctly because then I get an unrelated error ` TypeError: strapi.store is not a function` for the createUser function in factory.js. When I log Strapi while running the tests the object doesn't seem to have the .store property. Any idea what's going on here?

Some useful context might be that I'm running Strapi 4.2.2, because I can't update to the latest version due to an issue with building the admin panel in the latest version that hasn't been resolved

**Comment by qunabu** [comment]
https://github.com/qunabu/strapi-unit-test-example/pull/63#issuecomment-1268606038 4.2.2 seems to be working i cannot reproduce the issue

**Comment by aarbanas** [comment]
I am having the same Error using typescript version of tests. 
In `helpers/strapi.ts`, when strapi is starting in function `setupStrapi()` it catches exception with error: `SqliteError: create table 'public'.'strapi_migrations' ('id' integer not null primary key autoincrement, 'name' varchar(255), 'time' datetime) - unknown database 'public'`. 

I also have the same error as @callum-gander, when `.load()` is removed from `await Strapi()` than this error appears: `TypeError: strapi.store is not a function`. 

The version of strapi I am using is `4.3.9` and all the rest was configured the same as in this repo.
